@extends('layouts.app')

@section('title', 'Instructors | Kenosha Academy of Performing Arts')
@section('description', 'Learn About Our Team And How We Can Help You.')

@section('content')

    <div class="banner-wrap d-none d-md-block">
        <div class="banner"></div>
    </div>

    <div class="bg-white">
        <div class="container">
            <section class="section-teachers container">
                <section>
                    <h2 class="pt-5 pb-3 text-center">What We Believe</h2>
                    <div class="row">
                        <div class="col-sm">
                            <div>
                                <video controls style="height: auto; width: 100%;">
                                    <source src="/images/kapa-studio-story.mp4" type="video/mp4">
                                </video>
{{--                                <iframe src="https://player.vimeo.com/video/252797638" width="100%" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>--}}
                            </div>
                        </div>
                        <div class="col-sm d-flex align-items-center">
                            <p>
                                We believe that all students deserve a plan to feel safe and inspired to grow as artists. Through quality dance and music lessons in Kenosha WI we teach life lessons that foster community, develop leadership skills, self confidence, motivation, and creative thinking. Regardless of ability, all students will experience the joy of reaching his or her personal level of accomplishment and find a passion for the arts that will last a lifetime.
                                <br><br>
                                We strive to create a positive community for families through empathetic, attentive service and the understanding that each family’s educational needs are different. Parents will find a convenient location, friendly service, and welcoming atmosphere. We encourage a culture of interaction among families to create comfort, loyalty and value for everyone. Families stay with us because of our commitment to excellence and costumer care.
                            </p>
                        </div>
                    </div>
                    <h2 class="pt-5 pb-3 text-center">Meet The Team</h2>
                </section>
                <div class="container pb-5">
                    <x-instructor image="staff-annie.png" plug="Annie" name="Annie Hackett" title="Owner & KAPA Director" bio="Ms. Hackett is the owner and artistic director of the Kenosha Academy of Dance, Music & Drama, is a member of the Actor’s Equity Association and is a former professor of dance at Carthage College. She has also been a guest teacher at Columbia College and Roosevelt University. She and her studio have been featured in Dance Magazine and Dance Teacher Magazine. In her 30 years as a dance educator Ms. Hackett has taught workshops, master classes and at studios in her home state of New York as well as Chicago and it’s surrounding suburbs. Her choreography has been seen at Chicago area theaters. Ms. Hackett’s performing career includes many productions at theaters such as The Chicago Shakespeare Theater (Chicago, IL), The Marriott Lincolnshire Theatre (Chicago, IL), The Drury Lane Theater (Oakbrook, IL) The Drury Lane Theater South (Evergreen Park, IL), and The Fireside Playhouse (Ft. Atkinson, WI).. She has also performed for Carnival Cruise Lines and many industrial shows for organizations like State Farm, Pepsi, Give Kids the World, and Kraftmaid. Ms. Hackett is a veteran of additional regional theatre productions in New York and Florida, and industrial shows internationally. Her company experience includes, The Zodiaque Dance Company (Buffalo, NY), Buffalo Inner City Ballet (Buffalo,NY) and The Greater Buffalo Opera Corps de Ballet (Buffalo, NY). She attended the State University of New York at Buffalo."/>
                    <x-instructor image="staff-susan.png" plug="Susan" name="Susan Myers" title="Dance Instructor" bio="Susan Ojala Myers began her dance training at the Academy of Movement and Music, in Oak Park, Illinois, under the direction of Stephanie Clemens. She performed with the Lyric Opera of Chicago, as well as Momenta! performing arts company, dancing both new and historic works. Early on in her career, Susan realized that her true passion was teaching. She has been working with dancers of all ages and abilities for over 20 years, on the east coast, as well as in the midwest. Besides teaching in the dance studio world, she runs several outreach dance programs in local schools. Susan began her college studies at CalArts, and completed her BA in dance performance at Northern Illinois University. She is proud to have earned her level two certification in Autism Movement Therapy in 2015. She teaches AMT classes throughout the Kenosha area, including Open Wings Learning Community, where she also sits on the board of directors. Susan and her husband, Eric, live in the Kenosha area with their three children."/>
                    <x-instructor image="staff-jeri.jpg" plug="Jeri" name="Jeri Gray" title="Special Events Coordinator" bio="Bio coming soon!"/>
                    <x-instructor image="annette.jpg" plug="Annette" name="Annette Lawniczak" title="Dance Instructor, Education Director" bio="Annette Lawniczak received her BFA in dance performance, graduating magna cum laude, from Northern Illinois University. After graduation, she performed with several independent choreographers and became one of the founding members and Co-Artistic Director of Fox River Dance Company. In 2001, Annette began producing and directing her own annual dance performance, Freespace, a program in which pre-professional and professional students and choreographers collaborate and raise money for charity. Annette has been teaching and choreographing in the Chicagoland area and Wisconsin for over 20 years and formerly served as Ballet Mistress for RASA Dance Chicago, Executive Director and Director of Ballet for State Street Dance Studio, and Ballet Mistress and Company Administrator for NoMi Dance Chicago. In addition to teaching at Kenosha Academy of Performing Arts, she is the Ballet Mistress for Petite Pas Ballet School in Delafield, Wisconsin. Her choreography has been performed at the critically-acclaimed Dance Chicago Festival, Esencia Dance Festival and Chicago Freelance Dance."/>
                    <x-instructor image="staff-allison.jpg" plug="Allison" name="Allison Henes" title="General Manager" bio="Bio coming soon!"/>
                    <x-instructor image="haley.jpg" plug="Haley" name="Haley Moore" title="Dance Instructor, Special Programs Director" bio="Haley Moore was born and raised in Kenosha, WI, she began her dance education at the age of 7. Haley studied dance at our very own Kenosha Academy of Performing Arts from age 12 until graduating high school. Following graduation, Haley attended the University of Wisconsin- Milwaukee where she earned her Bachelor’s in Fine Arts (BFA) through UWM Dance Department’s contemporary dance/choreography track. Throughout her time at UWM, she performed in several works and productions choreographed by fellow BAF students, resident MFA students, and UWM professors. Haley has recently moved back to the Kenosha area to return the gift of dance to students of her own. She is very excited to take over both STAR Leadership and NHSDA programs this year at KAPA."/>
                    <x-instructor image="staff-laura.png" plug="Laura" name="Laura Williams" title="Dance Instructor" bio="Laura was born and raised in Muncie, IN where she started dancing at the age of 11. Laura studied Exercise Science at Ball State University in Muncie, IN and continued to work with her high school dance team by choreographing hip hop routines. In 2014 she began working for Inspire @ D.D.S (Dixie’s Dance Studio) where she taught hip hop and jazz classes. She worked closely with Inspire’s competition team by choreographing and cleaning/critiquing solos, hand picking and choreographing for a competitive Hip Hop Crew, working with the studio director on the studio production including 60+ dancers, and traveling to competitions throughout the U.S. In her last semester of school, Laura moved to Phoenix, Arizona where she completed an internship with Overcoming U: A Mindful Corporate Wellness, where she helped develop exercise and nutrition courses to be given to clients. She uses this knowledge while teaching her classes to make her dancers stronger and healthier. She continued to teach dance at Bricks Studio in Phoenix while completing her work with Overcoming U. At Bricks Studio, Laura took on the position of Recital Director for their 2018 Spring Recital. She spent her last year at Bricks Studio teaching beginning Ballet and Tap combo classes, recreational hip hop, a competitive Hip Hop Crew, ran the Mini Company rehearsals (ages 5-8), choreographed and cleaned solo routines, worked closely with the Company Director traveling to all competitions, all while ordering 800+ costumes and planning/directing the recital for the Spring. After the recital at Bricks Studio, Laura moved back to the midwest to be closer to family, but is excited to continue her journey in dance and inspiring children to find their love for dance!"/>
                    <x-instructor image="staff-sarah-dance.png" plug="Sarah" name="Sarah Nichols" title="Dance Instructor" bio="A Kenosha native, Sarah Nichols has studied dance since 1987 at Guy Singer Dance Studio with her primary focus being Tap. Sarah has competed in group and solo Jazz and Tap categories at the regional and national levels in Showstopper and I Love Dance competitions. Sarah has been sharing her love of dance, teaching children through adults, since 1998. Along with teaching dance, Sarah is a Director, Psychotherapist and Family Court Mediator at InterConnections, S.C., an out-patient mental health clinic in Kenosha, and a board member for Wisconsin InterProfessional Committee on Divorce (WIPCOD), a nonprofit organization in Wisconsin."/>
                    <x-instructor image="staff-sofia.png" plug="Sofia" name="Sofia Puterbaugh" title="Dance Instructor" bio="Sofia Puterbaugh is a graduate of University of Minnesota - Twin Cities with two degrees in Dance (BA) and Human Resources (BS). She is currently earning her Master's in School Counseling, plus her therapy license from DePaul University. Sofia has been teaching dance for eight years, and wants to create students who are passionate, compassionate, and creative. She wants to foster a classroom of love, respect, and driven dancers. Sofia is inspired not only to promote great dancing, but works to develop thoughtful and driven problem solvers and kind human beings! Sofia’s choreography credits include many musical theatre productions for the Kenosha Unified School District: West Side Story, Peter Pan, and Alice in Wonderland. She also has taught at a variety of studios in the Midwest in styles of Ballet, Jazz, Musical Theatre, Contemporary, Modern, Lyrical, and Tap. She has appeared in works by Sidra Bell, Michel Kouakou, Carl Flink, and Angharad Davies. She has studied under amazing mentors including: Erin Thompson, Annie Hackett, Valerie Gonzalez and Holly Stanfield. Sofia has had the pleasure of working at a variety of artistic organizations including Art Institute of Chicago, Navy Pier, Joffrey Ballet."/>
                    <x-instructor image="glass.jpg" plug="Felicia" name="Felicia Glass" title="Dance Instructor" bio="My name is Felicia. My students all call me Ms. FeFe. I grew up right here in Kenosha and started dancing in 6th grade at Sass Studios where I focused on Ballet, Jazz and Hip Hop. In exchange for taking classes at Sass, I started teaching Creative Movement to 4 and 5 year olds. That was my first introduction to teaching dance and I fell in love instantly. Throughout my schooling I was also involved in theatre and have been in several musical productions. I would later become choreographer for Children's Theatre Academy in Kenosha where I was responsible for choreographing full length musicals and teaching around 70+ children at a time! That experience was extremely rewarding and I'm grateful to have had the opportunity to work directly in my community. I'm thrilled to become a part of the KAPA community and will work to support all of your individual strengths and goals, not just in dance, but in life."/>
{{--                    <x-instructor image="angela.JPG" plug="Angela" name="Angela Konicki" title="Dance Instructor" bio="Bio coming soon!"/>--}}
                    <x-instructor image="liz.jpeg" plug="Liz" name="Liz Anderson" title="Dance Instructor" bio="Liz began her ballet training at Jacqueline’s School of Ballet in Lindon, UT. There, she trained classically for ten years until she was invited at age 16 to be an apprentice with Utah Regional Ballet, now Utah Metropolitan Ballet. Upon graduation, she continued to work with Utah Metropolitan Ballet and performed professionally for three seasons. During her performing career she had the privilege to study under and perform works by Alan Hineline, Jacqueline Colledge, Heather Gray, Shayla Bott, and many others. In addition to performing she had the opportunity to choreograph on the company and received honors at “Choreography Design Project”. Liz is a graduate of Utah Valley University where she studied ballet and community health concurrently on both ballet performance and academic scholarships. Shortly after graduating college, Liz met her husband Creighton. They were married and moved across the country to Wisconsin. Liz is the proud mama of 4 children, runs a baking business out of her home, and loves to be outside. She has been teaching ballet and piano for the past fourteen years and loves watching her students develop into talented artists and wonderful people!"/>
                    <x-instructor image="emily.jpeg" plug="Emily" name="Emily Marrese" title="Dance Instructor" bio="Emily Marrese graduated at Oklahoma City University where she received her Bachelor of Science in American Dance Pedagogy. She grew up training in Kenosha, Wisconsin and is a proud alumna of KAPA! While studying ballet, jazz, tap, and musical theater, she taught in the Community Dance Center at the Ann Lacy school of American Dance and Entertainment. It is with great honor that she has the privilege to do what she loves most each and every day. Being able to grow in genuine relationships right from the very moment she steps into the dance studio is why she wishes to better her community. Her philosophy will constantly evolve and blossom as she grows as an educator: striving to be the educator that turns people's interests into passions by guiding them to be more than just technical dancers but to uphold qualities of truth, honor, love, and passion in the studio and out. She is excited to be back at her home studio KAPA to share her love and passion for dance with her new students this year!"/>
                    <x-instructor image="kimberly.jpg" plug="Kimberly" name="Kimberly Balleza" title="Dance Instructor" bio="Kim started dancing at the age of 5, discovering her love of ballet.  She eventually added gymnastics and tumbling to her talents, as well as jazz dance.  She studied ballet briefly at Lou Conte Dance Studio in Chicago during college.  Her studies in tap, lyrical, hip hop, and ballroom came later after starting her family, and her love for teaching was born.  Kim continued to expand her dance studies from other local instructors, as well as taking master classes during conventions and at Broadway Dance Center in New York City.  She has taught various styles of dance for 15 years and has choreographed many competition routines, as well."/>
                    <x-instructor image="staff-talia.png" plug="Talia" name="Talia Larsen" title="Dance Instructor" bio="Talia Larsen, a former KAPA student, Classroom Assistant, Front Desk Host, and now Dance Teacher, has gone full circle with her involvement in the studio. Graduating from Carthage College with a Bachelor's Degree in Exercise Sport Science and a Minor in Dance, she is excited to incorporate her education and skills in her instruction at KAPA. Having learned to dance from the same teachers she’s now coworkers with shows the type of values that KAPA instills in their students: Creating relationships, a safe physical and mental environment, all while delivering quality instruction. Our studio is truly “More Than Just Great Dancing” and Talia’s values align entirely with these ideals. With an upbeat, fun spirited, high energy approach to teaching, her main goal is to teach kids to be just as amazing people as they are dancers. Outside of teaching she is pursuing a career in Physical Therapy, where she can develop techniques to help injured dancers/athletes. She is so excited to be in a position where she can help aspiring dancers be strong and confident in their approach to movement, while also growing as young people in our community."/>
                    <x-instructor image="staff-molly.JPG" plug="Molly" name="Molly Hill Fuller" title="Music Instructor" bio="MOLLY (HILL) FULLER, is an actor/singer/dancer originally from Goshen, IN and she is thrilled to teach music at KAPA! She is a proud graduate of Western Michigan University's BFA Musical Theatre Performance program. For the past three years, Molly has been an active actor/choreographer/director/youth educator at The Round Barn Theatre in Nappanee, IN, and spent this past summer performing with Northern Lakes Arts Association in Ely, MN as a member of their Broadway in the Boundary Waters Company (Godspell/Songs for a New World). Most recently, Molly made her professional directorial debut with The Secret Garden at the Round Barn Theatre. She also enjoys choreographing musicals, concerts, and show choir selections at Huntington University and Goshen High School. Molly's favorite performance credits include Ariel in The Little Mermaid (RBT), Julie Jordan in Carousel (RBT), Sally in You're a Good Man Charlie Brown (RBT), Logainne in The 25th Annual Putnam County Spelling Bee (The Barn Theatre) for which she received a Wilde Award for Best Supporting Actress, Lilly in Lilly’s Purple Plastic Purse (Farmers Alley Theatre), Little Sally in Urinetown (WMU), and Debbie Reynolds in What a Glorious Feeling (North Coast Theatre Festival). Molly is so excited to be at Carthage College this year to grow as a teaching artist and performer! As a teaching artist, Molly has directed three full summer youth productions: Frozen Kids!, You’re a Good Man Charlie Brown, and Moana Jr., led masterclasses and private lessons, given workshops with area schools to aid with the college audition process, and choreographed numerous dance classes and summer youth programming at The Goshen Theatre, the Round Barn Theatre, and Northern Lakes Arts Association. When Molly isn't performing you can find her teaching fitness classes and enjoying married life with her husband, Ethan!"/>
{{--                    <x-instructor image="" plug="" name="" title="" bio=""/>--}}

                    <div class="row mt-4">
                        @include('april')
                    </div>

                </div>
            </section>
        </div>
    </div>

    <div class="banner-wrap d-none d-md-block">
        <div class="banner"></div>
    </div>

@endsection
